name: Daily Run

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow
    
jobs:
  build:
    runs-on: ubuntu-latest

    environment: env  # Specify the environment for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        DISCORD_AUTH_KEY: ${{ secrets.DISCORD_AUTH_KEY }}
      run: |
        python main.py